// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ADirectoryTree: typeof import('ant-design-vue/es')['DirectoryTree']
    AForm: typeof import('ant-design-vue/es')['Form']
    AFormItem: typeof import('ant-design-vue/es')['FormItem']
    AImage: typeof import('ant-design-vue/es')['Image']
    AInput: typeof import('ant-design-vue/es')['Input']
    AInputPassword: typeof import('ant-design-vue/es')['InputPassword']
    AMenu: typeof import('ant-design-vue/es')['Menu']
    AMenuItem: typeof import('ant-design-vue/es')['MenuItem']
    AModal: typeof import('ant-design-vue/es')['Modal']
    APopover: typeof import('ant-design-vue/es')['Popover']
    ASelect: typeof import('ant-design-vue/es')['Select']
    ASpin: typeof import('ant-design-vue/es')['Spin']
    ATable: typeof import('ant-design-vue/es')['Table']
    ATooltip: typeof import('ant-design-vue/es')['Tooltip']
    ATreeSelect: typeof import('ant-design-vue/es')['TreeSelect']
    BomDetailBottomTable: typeof import('./src/components/bom_detail/BomDetailBottomTable.vue')['default']
    BomDetailTopTable: typeof import('./src/components/bom_detail/BomDetailTopTable.vue')['default']
    ChangeImg: typeof import('./src/components/personal/ChangeImg.vue')['default']
    CoreChart: typeof import('./src/components/trend_chart/CoreChart.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    MaterialHeader: typeof import('./src/components/query_material/MaterialHeader.vue')['default']
    MaterialTable: typeof import('./src/components/query_material/MaterialTable.vue')['default']
    ModelTitle: typeof import('./src/components/query_material/ModelTitle.vue')['default']
    PasswordInput: typeof import('./src/components/personal/PasswordInput.vue')['default']
    QueryBomHeader: typeof import('./src/components/query_bom/QueryBomHeader.vue')['default']
    QueryBomTable: typeof import('./src/components/query_bom/QueryBomTable.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableBodyCell: typeof import('./src/components/TableBodyCell.vue')['default']
    TrendTable: typeof import('./src/components/trend_chart/TrendTable.vue')['default']
  }
}

export { }
